#!/bin/bash
#BSUB -J mytest
#BSUB -q debug
#BSUB -n 2
#BSUB -W 00:02
#BSUB -e %J.err
#BSUB -o %J.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 2 ./ex4.out -n 10000 \
  -ksp_type gmres \
  -ksp_gmres_restart 30 \
  -ksp_rtol 1.0e-10 \
  -ksp_atol 1.0e-50 \
  -ksp_max_it 1500 \
  -pc_type hypre \
  -ksp_monitor_short \
  -ksp_converged_reason \
  -ksp_view \
  -log_view > $LSB_JOBID.log 2>&1

