#!/bin/bash

#BSUB -J mytest
#BSUB -q debug
#BSUB -n 1
#BSUB -W 00:05
#BSUB -e log
#BSUB -o log
#BSUB -R "span[ptile=1]"
#BSUB -m "r13n45"

# Non-vectorized code
/usr/bin/time -f "simple2_no_vec: %e" ./simple2_no_vec

# Standard SSE vectorized code
/usr/bin/time -f "simple2: %e" ./simple2

# AVX-512 vectorized code
/usr/bin/time -f "simple2_avx512: %e" ./simple2_avx512

# AVX-512 vectorized code, with tweaks
/usr/bin/time -f "simple2_zmm_hi: %e" ./simple2_zmm_hi

#numactl --hardware
